apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: randomlyright-ingress
  namespace: "2401108"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: randomlyright.imcc.com 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: randomlyright-service
                port:
                  number: 80